# This file is part of Percona Server for MongoDB.
#
# Copyright (C) 2019-present Percona and/or its affiliates. All rights reserved.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the Server Side Public License, version 1,
#    as published by MongoDB, Inc.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    Server Side Public License for more details.
#
#    You should have received a copy of the Server Side Public License
#    along with this program. If not, see
#    <http://www.mongodb.com/licensing/server-side-public-license>.
#
#    As a special exception, the copyright holders give permission to link the
#    code of portions of this program with the OpenSSL library under certain
#    conditions as described in each individual source file and distribute
#    linked combinations including the program with the OpenSSL library. You
#    must comply with the Server Side Public License in all respects for
#    all of the code used other than as permitted herein. If you modify file(s)
#    with this exception, you may extend this exception to your version of the
#    file(s), but you are not obligated to do so. If you do not wish to do so,
#    delete this exception statement from your version. If you delete this
#    exception statement from all source files in the program, then also delete
#    it in the license file.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/ldap_options.h"
    configs:
        section: 'LDAP options'
        source: [ yaml, cli ]
#        initializer:
#            register: addLDAPOptions

server_parameters:
    ldapServers:
        description: "Comma separated list of LDAP servers"
        set_at: runtime
        cpp_varname: "ldapGlobalParams.ldapServers"
    ldapTimeoutMS:
        description: "Timeout to wait for response from LDAP server in millisecons. Default is 10000"
        set_at: runtime
        cpp_varname: "ldapGlobalParams.ldapTimeoutMS"
        default: 10000
    ldapQueryUser:
        description: "LDAP user used to connect or query LDAP server"
        set_at: runtime
        cpp_varname: "ldapGlobalParams.ldapQueryUser"
    ldapQueryPassword:
        description: "Password used with queryUser to bind to an LDAP server"
        set_at: runtime
        cpp_varname: "ldapGlobalParams.ldapQueryPassword"
        redact: true
    ldapUserToDNMapping:
        description: "Provides mechanism to transform authenticated user name to a LDAP Distinguished Name (DN)"
        set_at: runtime
        cpp_varname: "ldapGlobalParams.ldapUserToDNMapping"
        default: "[{match: \"(.+)\", substitution: \"{0}\"}]"
    ldapUseConnectionPool:
        description: ""
        set_at: startup
        cpp_varname: "ldapGlobalParams.ldapUseConnectionPool"
    ldapUserCacheInvalidationInterval:
        description: ""
        set_at: [startup, runtime]
        cpp_varname: "ldapGlobalParams.ldapUserCacheInvalidationInterval"
        default: 30

configs:
    'security.ldap.servers':
        description: 'Comma separated list of LDAP servers in format host:port'
        short_name: ldapServers
        arg_vartype: String
    'security.ldap.transportSecurity':
        description: 'Default is tls to use TLS secured connection to LDAP server. To disable it use none'
        short_name: ldapTransportSecurity
        arg_vartype: String
        default: tls
    'security.ldap.bind.method':
        description: 'The method used to authenticate to an LDAP server. simple or sasl. Default is simple'
        short_name: ldapBindMethod
        arg_vartype: String
        default: simple
    'security.ldap.bind.saslMechanisms':
        description: 'Comma-separated list of SASL mechanisms which can be used to authenticate to an LDAP server. Default is DIGEST-MD5'
        short_name: ldapBindSaslMechanisms
        arg_vartype: String
        default: DIGEST-MD5
    'security.ldap.timeoutMS':
        description: 'Timeout to wait for response from LDAP server in millisecons. Default is 10000'
        short_name: ldapTimeoutMS
        arg_vartype: Int
    'security.ldap.bind.queryUser':
        description: 'LDAP user used to connect or query LDAP server'
        short_name: ldapQueryUser
        arg_vartype: String
    'security.ldap.bind.queryPassword':
        description: 'Password used with queryUser to bind to an LDAP server'
        short_name: ldapQueryPassword
        arg_vartype: String
        implicit: ''
        redact: true
    'security.ldap.userToDNMapping':
        description: 'Provides mechanism to transform authenticated user name to a LDAP Distinguished Name (DN)'
        short_name: ldapUserToDNMapping
        arg_vartype: String

