# This file is part of Percona Server for MongoDB.
#
# Copyright (C) 2018-present Percona and/or its affiliates. All rights reserved.
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the Server Side Public License, version 1,
#    as published by MongoDB, Inc.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    Server Side Public License for more details.
#
#    You should have received a copy of the Server Side Public License
#    along with this program. If not, see
#    <http://www.mongodb.com/licensing/server-side-public-license>.
#
#    As a special exception, the copyright holders give permission to link the
#    code of portions of this program with the OpenSSL library under certain
#    conditions as described in each individual source file and distribute
#    linked combinations including the program with the OpenSSL library. You
#    must comply with the Server Side Public License in all respects for
#    all of the code used other than as permitted herein. If you modify file(s)
#    with this exception, you may extend this exception to your version of the
#    file(s), but you are not obligated to do so. If you do not wish to do so,
#    delete this exception statement from your version. If you delete this
#    exception statement from all source files in the program, then also delete
#    it in the license file.
#

global:
    cpp_namespace: "mongo"
    cpp_includes:
        - "mongo/db/storage/inmemory/inmemory_global_options.h"
    configs:
        section: 'InMemory options'
        source: [ cli, ini, yaml ]

configs:
    # inMemory storage engine options
    "storage.inMemory.engineConfig.inMemorySizeGB":
        description: >-
            The maximum memory in gigabytes to use for InMemory storage.
            See documentation for default.
        arg_vartype: Double
        cpp_varname: 'inMemoryGlobalOptions.cacheSizeGB'
        short_name: inMemorySizeGB
    "storage.inMemory.engineConfig.statisticsLogDelaySecs":
        description: >-
            The number of seconds between writes to statistics log.
            If 0 is specified then statistics will not be logged.
        arg_vartype: Int
        cpp_varname: 'inMemoryGlobalOptions.statisticsLogDelaySecs'
        short_name: inMemoryStatisticsLogDelaySecs
        hidden: true
        validator:
            gte: 0
            lte: 100000
        default: 0
    "storage.inMemory.engineConfig.configString":
        description: 'InMemory storage engine custom configuration settings'
        arg_vartype: String
        cpp_varname: 'inMemoryGlobalOptions.engineConfig'
        short_name: inMemoryEngineConfigString
        hidden: true
    "storage.inMemory.collectionConfig.configString":
        description: 'InMemory custom collection configuration settings'
        arg_vartype: String
        cpp_varname: 'inMemoryGlobalOptions.collectionConfig'
        short_name: inMemoryCollectionConfigString
        hidden: true
    "storage.inMemory.indexConfig.configString":
        description: 'InMemory custom index configuration settings'
        arg_vartype: String
        cpp_varname: 'inMemoryGlobalOptions.indexConfig'
        short_name: inMemoryIndexConfigString
        hidden: true
